 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

model:
  arch: blip2
  model_type: pretrain

  pre_align: False
  freeze_encoder: True
  load_pretrained: True
  load_finetuned: False
  num_query_token: 32
  embed_dim: 256
  max_txt_len: 32
  cross_attention_freq: 2
  video_encoder_embed: 1024
  audio_encoder_embed: 768
  vit_config: "/mnt/ha/bd2/LAVIS/mm_llm/configs/video_config.json"
  aud_config: "/mnt/ha/bd2/LAVIS/mm_llm/configs/audio_config.json"
  vit_pretrained: "/mnt/ha/bd2/LAVIS/mm_llm/ckpt/encoder_ckpt/vit3d.pth"
  aud_pretrained: "/mnt/ha/bd2/LAVIS/mm_llm/ckpt/encoder_ckpt/beats.pt"
  bert_pretrained: "/mnt/ha/bd2/LAVIS/mm_llm/ckpt/bert/bert-base-cased"
  qformer_pretrained: "/mnt/ha/bd2/LAVIS/mm_llm/ckpt/qformer/blip2_pretrained.pth"

datasets:

  coco_caption:
    vis_processor:
        train:
          name: "blip2_image_train"
          image_size: 224
    text_processor:
        train:
          name: "blip_caption"
  vg_caption:
    vis_processor:
        train:
          name: "blip_image_train"
          image_size: 224
    text_processor:
        train:
          name: "blip_caption"

run:
  task: image_text_pretrain
  itc: False
  itm: True
  root_dir: '/mnt/ha/bd2/data'
  data_path: '/coco_vat_9/'
  ann_path: '/coco_vat_9.json'

  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 3e-4
  min_lr: 3e-5
  warmup_lr: 3e-6

  weight_decay: 0.05
  max_epoch: 32
  batch_size: 32
  num_workers: 4
  warmup_steps: 5000

  seed: 42
  library_dir: ""
  output_dir: "/mnt/ha/bd2/LAVIS/mm_llm/output1/noitc/"

  amp: True
  resume_ckpt_path: null

  evaluate: False 
  train_splits: ["train"]

  device: "cuda"
  world_size: 8
  dist_url: "env://"
  distributed: True